services:
  server:
    build: 
      context: ./Server
      dockerfile: Dockerfile.prod
    ports:
      - "5100:5100"
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - server