services:
  server:
    build: 
      context: ./Server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - server