# Use a Node.js base image
FROM node:22

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

#Install nodemon
RUN npm install -g nodemon

# Copy all source files
COPY . .

# Command to run the development server
CMD ["npm", "run", "dev"]