# Use an official Node runtime as the base image
FROM node:22

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Make port 5000 available outside the container
EXPOSE 5100

# Define the command to run the app
CMD ["npm", "start"]